### ISSUE TITLE
question about code

### ISSUE THREAD

**Issue by rumtsv** [limz1986/Portolio_Optimisation_Efficient_Froniter_ESG#1]
Hello! I am writing a paper at the university on ESG.Could you please tell me what fragment of your code contains information on COVID - 19 influence on stock market? Maybe you could specify what impact you've noticed during you research?

Best regards

**Comment by limz1986** [comment]
It's not code, it's actually data, it's the shock in the fed interest rates and also the increase in standard deviation of various stock prices when you use the code to pull out returns pre and during covid

**Comment by limz1986** [comment]
The programme just runs on what values you feed in, it simulates the optimal portfolio over a certain time period

**Comment by rumtsv** [comment]
Thanks a lot for your answer
